// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  allproducts: dynamic(() => import("./Allproducts")),
  clients: dynamic(() => import("./Clients")),
  enquiry: dynamic(() => import("./Enquiry")),
  hero: dynamic(() => import("./Hero")),
  homeproducts: dynamic(() => import("./Homeproducts")),
  homeservices: dynamic(() => import("./Homeservices")),
  misson: dynamic(() => import("./Misson")),
  whyus: dynamic(() => import("./Whyus")),
};
